### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by boldijar** [dandar3/android-support-v7-recyclerview#1]
![capture](https://cloud.githubusercontent.com/assets/7826299/7725095/23869242-ff00-11e4-9976-733881d1fb39.PNG)

Layout:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
android:paddingBottom="@dimen/activity_vertical_margin"
android:paddingLeft="@dimen/activity_horizontal_margin"
android:paddingRight="@dimen/activity_horizontal_margin"
android:paddingTop="@dimen/activity_vertical_margin"
tools:context="com.lifegoals.app.YourGoalsActivity" >

<android.support.v7.widget.RecyclerView
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

Error:
Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.v7.widget.RecyclerView

**Comment by dandar3** [comment]
I can't really say without the full stack trace but you may require the `support-v4` library as well - see [dandar3/android-support-v4](https://github.com/dandar3/android-support-v4) project or download directly into your `libs` project folder using the `Android Tools > Add support library` project context menu, or if you have it already make sure it matches the version of RecyclerView project.

**Comment by boldijar** [comment]
I finally added the recyclerview with the jars from bundle/extras..../support/.../recyclerview jar, and same for support 4.

Thanks anyways!

**Comment by dandar3** [comment]
Good stuff, thanks!
